name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16 # Altere para a versão do Node.js usada no seu projeto

      # 3. Install dependencies
      - name: Install Dependencies
        run: npm install

      # 4. Update version (auto-increment patch version)
      - name: Update Version
        run: |
          npm version patch --no-git-tag-version
          git add package.json package-lock.json
          git commit -m "ci: bump version [skip ci]"

      # 5. Build the project
      - name: Build Project
        run: npm run build

      # 6. Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
